parameters:
  ns_util.example.class: NS\UtilBundle\Example

services:
  ns.form.dateclockpicker:
    class: NS\UtilBundle\Form\Types\DateClockPicker
    tags:
      - { name: form.type, alias: dateclockpicker }
  ns.form.clockpicker:
    class: NS\UtilBundle\Form\Types\ClockPicker
    tags:
      - { name: form.type, alias: clockpicker }
  ns.form.datepicker:
      class: NS\UtilBundle\Form\Types\DatePickerType
      tags:
        - { name: form.type, alias: datepicker }
  ns.form.types.autocomplete:
      class: NS\UtilBundle\Form\Types\Autocomplete
      arguments: ["@doctrine.orm.entity_manager", "@router" ]
      tags:
        - { name: form.type, alias: ns_autocomplete }
  ns.ajax_autocompleter:
    class: NS\UtilBundle\Service\Ajax
    arguments: [ "@doctrine.orm.entity_manager", "@request", "@templating" ]
    scope: request
