parameters:
  ns_util.example.class: NS\UtilBundle\Example

services:
#  ns_util.example:
#    class: "%ns_util.example.class%"
#    arguments: [ "@service_id", plain_value, "%parameter_name%" ]
  ns.ajax_autocompleter:
    class: NS\UtilBundle\Service\Ajax
    arguments: [ "@ns.model_manager", "@request" ]
    scope: request
