parameters:
  ns_util.model_manager.service: "@doctrine.orm.entity_manager"

services:
  ns.form.dateclockpicker:
    class: NS\UtilBundle\Form\Types\DateClockPicker
    tags:
      - { name: form.type, alias: dateclockpicker }
  ns.form.clockpicker:
    class: NS\UtilBundle\Form\Types\ClockPicker
    tags:
      - { name: form.type, alias: clockpicker }
  ns.form.datepicker:
      class: NS\UtilBundle\Form\Types\DatePickerType
      tags:
        - { name: form.type, alias: datepicker }
  ns.form.types.autocomplete:
      class: NS\UtilBundle\Form\Types\Autocomplete
      arguments: [ %ns_util.model_manager.service%, "@router" ]
      tags:
        - { name: form.type, alias: ns_autocomplete }
  ns.ajax_autocompleter:
    class: NS\UtilBundle\Service\Ajax
    arguments: [ %ns_util.model_manager.service%, "@request", "@templating" ]
    scope: request
